# Generated by Django 2.1.3 on 2018-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmentgo', '0002_auto_20181103_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='invasive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
